<section class="row">
    <div class="col-4 offset-4">
        <div class="card card-body">
            <h1>Cadastro de Usuário</h1>
            <hr>

            <form action="" method="post">
                <input name="nome" type="text" class="form-control form-control-lg mb-3" placeholder="Nome">

                <input name="email" type="email" class="form-control form-control-lg mb-3" placeholder="Email">
    
                <input name="senha" type="password" class="form-control form-control-lg mb-3" placeholder="Senha">
    
                <button class="btn btn-primary btn-lg w-100">ENTRAR</button>

                <p class="mt-3 text-end">
                    Já tem conta? <br>
                    <a href="/">Login</a>
                </p>
            </form>
        </div>
    </div>
</section>