<?php
    if (false === empty($_POST)) {
        //recebendo os dados que vieram do form do HTML
        $name = $_POST['name'];
        $email = $_POST['email'];
        $phone = $_POST['phone'];

        $sql = "
            INSERT INTO tb_contatos (nome, email, telefone)
            VALUES ('{$name}', '{$email}', '{$phone}');
        ";

        include '../src/conexao.php';

        // esse codigo é sujeito a ataques SQL Injection
        $pdo->query($sql);

        echo "<div class='alert alert-success'>
            <strong>Pronto!</strong>
            Novo contatinho inserido 😈 🔥<br>
            <em>{$name}</em>
        </div>";
    }
?>

<section class="card card-body shadow">
    <h2> 
        <i class="material-icons fs-2">person_add</i>
        Cadastro
    </h2>

    <div class="row my-3 pt-5 align-items-center">
        <div class="col">
            <img src="/img/add.svg" width="80%" alt="">
        </div>
        <div class="col">
            <form action="" method="post">
                <label for="name">Nome</label>
                <input name="name" type="text" id="name" class="form-control mb-2" placeholder="Digite aqui">
                
                <label for="email">Email</label>
                <input name="email" type="text" id="email" class="form-control mb-2" placeholder="Digite aqui">
                
                <label for="phone">Telefone</label>
                <input name="phone" type="text" id="phone" class="form-control mb-3" placeholder="Digite aqui">

                <button class="btn btn-primary w-100">PRONTO</button>
            </form>
        </div>
    </div>

</section>