<section class="card card-body shadow">
    <h1>Listar</h1>
    <hr>

    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                //ele traz a variavel $pdo pra ca
                include '../src/conexao.php';

                $resultado = $pdo->query('SELECT * FROM tb_contatos');

                $dados = $resultado->fetchAll(PDO::FETCH_ASSOC);

                foreach ($dados as $cada) {
                    echo "
                        <tr>
                            <td>{$cada['nome']}</td>
                            <td>{$cada['email']}</td>
                            <td>{$cada['telefone']}</td>
                            <td>
                                <a href='#' class='btn btn-sm btn-warning'>Editar</a>
                                <a href='#' class='btn btn-sm btn-danger'>Excluir</a>
                            </td>
                        </tr>
                    ";
                }
            ?>
        </tbody>
    </table>
</section>

