<?php

if (false === empty($_POST)) {
    include '../src/conexao.php';

    $email = parameter('email');
    $senha = parameter('senha');

    // usuario nao existe
    $sql = 'SELECT * FROM tb_usuarios WHERE email=:email';

    $statement = $pdo->prepare($sql);
    $statement->execute([
        ':email' => $email,
    ]);

    $user = $statement->fetch(PDO::FETCH_ASSOC);

    if ($user === false) {
        echo "
            <div class='alert alert-danger mt-5'>
                <strong>Vish!</strong>
                Usuário não encontrado
            </div>
        ";
    }

    if ($user !== false) {
        $verificacaoSenha = password_verify($senha, $user['senha']);
        
        if ($verificacaoSenha === true) {
            // usuario existe e senha confere
            $_SESSION['user'] = [
                'id' => $user['id'],
                'nome' => $user['nome'],
            ];
            
            header('location: /');
        } else {
            // usuario existe, e a senha nao confere
            echo "
                <div class='alert alert-danger mt-5'>
                    <strong>Vish!</strong>
                    Senha Incorreta
                </div>
            ";
        }
    }

}
?>

<section class="row">
    <div class="col-4 offset-4 mt-5">
        <div class="card card-body mt-5">
            <h1>Login</h1>
            <hr>
            <form action="" method="post">
                <input name="email" type="email" class="form-control form-control-lg mb-3" placeholder="Email">
    
                <input name="senha" type="password" class="form-control form-control-lg mb-3" placeholder="Senha">
    
                <button class="btn btn-primary btn-lg w-100">ENTRAR</button>

                <p class="mt-3 text-end">
                    Não tem conta? <br>
                    <a href="/cadastro">Cadastre-se</a>
                </p>
            </form>
        </div>
    </div>
</section>