<section class="row">
    <div class="col-4 offset-4">
        <div class="card card-body">
            <form action="" method="post">
                <input name="email" type="email" class="form-control form-control-lg mb-3" placeholder="Email">
    
                <input name="senha" type="password" class="form-control form-control-lg mb-3" placeholder="Senha">
    
                <button class="btn btn-primary btn-lg w-100">ENTRAR</button>

                <p class="mt-3 text-end">
                    Não tem conta? <br>
                    <a href="/cadastro">Cadastre-se</a>
                </p>
            </form>
        </div>
    </div>
</section>