<hr>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <i class="material-icons fs-1">groups</i>
      Contatinhos
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav me-auto">
        <a class="nav-link active" href="/">
          <i class="material-icons">home</i>
          Início
        </a>

        <a class="nav-link active" href="/contatos/cadastro">
          <i class="material-icons">person_add</i>
          Cadastrar
        </a>

        <a class="nav-link active" href="/contatos/listar">
          <i class="material-icons">person_search</i>
          Listar
        </a>
      </div>

      <div class="dropdown">
        <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="material-icons">person</i>
          <?php echo $_SESSION['user']['nome']; ?>
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><a class="dropdown-item" href="/usuario/perfil">Perfil</a></li>
          <li><a class="dropdown-item" href="/sair">Sair</a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>
