<hr>

<div class="row align-items-center">
    <div class="col">
        <h1> 
            <i class="material-icons fs-1">groups</i>
            CONTATINHOS
        </h1>
    </div>
    <div class="col text-end">
        <a class="btn btn-outline-dark" href="/">
            <i class="material-icons">home</i>
            Inicio
        </a>
        <a class="btn btn-outline-dark" href="/contatos/cadastro">
            <i class="material-icons">person_add</i>
            Cadastrar
        </a>
        <a class="btn btn-outline-dark" href="/contatos/listar">
            <i class="material-icons">person_search</i>
            Listar
        </a>
        <a class="btn btn-outline-danger" href="/sair">
            <i class="material-icons">logout</i>
            Sair
        </a>
    </div>
</div>
<hr>